### ISSUE TITLE
Impossible to plan a trip between a bikeshare station defined using text search and a destination bikeshare station from the map

### ISSUE THREAD

**Issue by kalon33** [mecatran/OpenTripPlanner-client-gwt#3]
It is impossible to plan a trip between a bikeshare station defined using the text search and a destination bikeshare station defined on the map. Trip is not calculated when clicking on "Plan route" button.

**Comment by laurentg** [comment]
@kalon33 I just tested this, and it works fine (between "Place Tourny" and "Bourranville"). With which station do you have the problem?

**Comment by kalon33** [comment]
@laurentg try 20001 - PLACE DE LA NATION on http://plannerparis.acolytesanonymes.org as start, and some other one as destination (I tried 3 different destinations with the same error)

**Comment by laurentg** [comment]
@kalon33 I just tried this start with various ends, and it works fine (at least I get a route with bike-share, transit, walk, etc...). You have to select a destination at least some distance away; otherwise the penalty associated with renting a bike will make you walk instead if the time gain is not sufficient.

**Comment by laurentg** [comment]
@kalon33 Do you still have this issue? I think we can close it.

**Comment by kalon33** [comment]
Sure we can, this seems linked to the "HTTPS Everywhere" related issue. I didn't encountered it again since.
